### ISSUE TITLE
Medium articles

### ISSUE THREAD

**Issue by chatman-media** [nareshbhatia/graphql-bookstore#12]
Hello. I noticed they you were banned on medium.com, was it resonable? Is there any place where I can find your graphql and ddd articles?

**Comment by nareshbhatia** [comment]
Thank you for bringing this to my attention, @zishe. I was completely unaware of this! I have emailed medium support and will let you know when they have fixed this issue. In the meanwhile you can access the DDD articles at my [personal blog](https://archfirst.org/). Unfortunately the GraphQL articles were only published on medium.

**Comment by chatman-media** [comment]
You are welcome! I hipe they will handle this problem soon.

**Comment by nareshbhatia** [comment]
Hi @zishe, Medium has fixed the issue on their side. Please let me know if you can access the articles.

**Comment by chatman-media** [comment]
All cool, thanks.
