### ISSUE TITLE
Can't build a production version of the server using tsc

### ISSUE THREAD

**Issue by nareshbhatia** [nareshbhatia/graphql-bookstore#3]
Can't build `apollo-bookstore-server` using the typescript compiler. It cannot find modules in the `node_modules` folder, e.g.

> src/graphql/pubsub.ts:2:24 - error TS2307: Cannot find module 'apollo-server'
 src/graphql/resolvers.ts:1:44 - error TS2307: Cannot find module 'merge-graphql-schemas'

I can only run the server with `ts-node`, which does not have these issues

**Comment by zishe** [comment]
I added PR to fix this.

**Comment by nareshbhatia** [comment]
Thanks @zishe. I merged the PR, but still having build issues. Here are the errors I am getting when doing `yarn build`:

```
node_modules/@apollographql/apollo-tools/lib/schema/resolveObject.d.ts:3:16 - error TS2665: Invalid module name in augmentation. Module 'graphql/type/definition' resolves to an untyped module at '/Users/narbhati/projects/graphql-bookstore/apollo-bookstore-server/node_modules/graphql/type/definition.js', which cannot be augmented.

3 declare module "graphql/type/definition" {
                 ~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@apollographql/apollo-tools/lib/utilities/graphql.d.ts:2:16 - error TS2665: Invalid module name in augmentation. Module 'graphql/language/predicates' resolves to an untyped module at '/Users/narbhati/projects/graphql-bookstore/apollo-bookstore-server/node_modules/graphql/language/predicates.js', which cannot be augmented.

2 declare module "graphql/language/predicates" {
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/apollo-cache-control/dist/index.d.ts:22:16 - error TS2665: Invalid module name in augmentation. Module 'graphql/type/definition' resolves to an untyped module at 'graphql-bookstore/apollo-bookstore-server/node_modules/graphql/type/definition.js', which cannot be augmented.

22 declare module 'graphql/type/definition' {
                  ~~~~~~~~~~~~~~~~~~~~~~~~~


Found 3 errors.
```

**Comment by nareshbhatia** [comment]
@zishe, I was able to get rid of the 3 errors by adding a dependency to `@types/graphql`. However, node still cannot run the production build because the emitted code contains `import` statements. (I had previously set the target to es6 just to get the compile going.)

Apparently, many people are having issues running Apollo server with TypeScript. See https://github.com/apollographql/apollo-server/issues/1606. I have added my comment to this issue.

**Comment by zishe** [comment]
@nareshbhatia, I also added `@types/graphql`, forgot to mention. But since you use `node.js` is it maybe OK to use `es6`?

**Comment by nareshbhatia** [comment]
Other issues related to this one:
- https://github.com/apollographql/apollo-server/issues/2332
- https://github.com/Urigo/merge-graphql-schemas/issues/155

**Comment by nareshbhatia** [comment]
Fixed. Needed to copy typedef files to dist folder.
